# Example 1: Throwing a Ball

### Q:- A ball is thrown straight up, from 3 m above the ground, with a velocity of 14 m/s. When does it hit the ground?


Ignoring air resistance, we can work out its height by adding up these three things:
(Note: t is time in seconds)

```python
The height starts at 3 m:	 	                                                      3
It travels upwards at 14 meters per second (14 m/s):	 	                          14t
Gravity pulls it down, changing its position by about 5 m per second squared:	 	−5t2
```
**Note for the enthusiastic: the -5t2 is simplified from -(½)at2 with a=9.8 m/s2)**	

### Instructions
* Add them up and save it as height `h`
* Write the quadratic equation in standard form when the ball hits the ground when the height is `0`
* The quadratic equation that you will be solving is `5t^2 -14t - 3 = 0`
* Make an array `coeff` to store the coefficients `(5,-14, -3)` of the quadratic equation
* Pass this array `coeff` as argument to `np.roots()` method which will return the roots for the quadratic equation   5t^2 -14t - 3 = 0. Save it as roots
* Print out `roots` to see your result

In [1]:
# import packages
import numpy as np

# Code starts here
h = 3+14+5
coeff = (5,-14,-3)
roots = np.roots(coeff)
roots

array([ 3. , -0.2])

The "t = −0.2" is a negative time, impossible in our case.

The "t = 3" is the answer we want:The ball hits the ground after 3 seconds!

Here is the graph of the Parabola h = −5t2 + 14t + 3
![](quadratic-1a.gif)

It shows you the height of the ball vs time

Some interesting points:

(0,3) When t=0 (at the start) the ball is at 3 m

(−0.2,0) says that −0.2 seconds BEFORE we threw the ball it was at ground level. This never happened! So our common sense says to ignore it.

(3,0) says that at 3 seconds the ball is at ground level.

Also notice that the ball goes nearly 13 meters high.

## Example 2: Statistics on Volleyball 

## 1. Calculate VolleyBall Players height?
The height is expressed in inches. Can you make a numpy array out of it and convert the units to meters?
### Instructions

* Create a numpy array from `height_inches`. Name this new array `np_height_inches`.
* Print `np_height_inches`.
* Multiply `np_height_inches` with `0.0254` to convert all height measurements from inches to meters. Store the new   values in a new array, `np_height_metres`.
* Print out `np_height_metres` and check if the output makes sense.

In [2]:
# height is available as a regular list
height_inches = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69,70, 73,75, 78, 79, 76, 74, 
          76, 72, 71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 74,69, 71, 74, 73, 73, 76, 74, 
          74, 70, 72, 77, 74, 70, 73, 75, 76, 76,78, 74, 74, 76, 77, 81, 78, 75, 77, 75, 76, 74, 
          72, 72, 75, 73, 73, 73, 70, 70, 70,76, 68, 71, 72, 75, 75, 75, 75, 68, 74, 78, 71, 73, 
          76, 74, 74, 79, 75, 73, 76, 74, 74, 73, 72, 74, 73, 74, 72, 73, 69, 72, 73, 75, 75, 73, 
          72, 72, 76, 74, 72, 77,74, 77, 75, 76, 80, 74, 74, 75, 78, 73, 73, 74, 75, 76, 71, 73]


# Import numpy
np_height_inches = np.array(height_inches)
print(np_height_inches)
np_height_meters = np_height_inches*0.0254
print(np_height_meters)

[74 74 72 72 73 69 69 71 76 71 73 73 74 74 69 70 73 75 78 79 76 74 76 72
 71 75 77 74 73 74 78 73 75 73 75 75 74 69 71 74 73 73 76 74 74 70 72 77
 74 70 73 75 76 76 78 74 74 76 77 81 78 75 77 75 76 74 72 72 75 73 73 73
 70 70 70 76 68 71 72 75 75 75 75 68 74 78 71 73 76 74 74 79 75 73 76 74
 74 73 72 74 73 74 72 73 69 72 73 75 75 73 72 72 76 74 72 77 74 77 75 76
 80 74 74 75 78 73 73 74 75 76 71 73]
[1.8796 1.8796 1.8288 1.8288 1.8542 1.7526 1.7526 1.8034 1.9304 1.8034
 1.8542 1.8542 1.8796 1.8796 1.7526 1.778  1.8542 1.905  1.9812 2.0066
 1.9304 1.8796 1.9304 1.8288 1.8034 1.905  1.9558 1.8796 1.8542 1.8796
 1.9812 1.8542 1.905  1.8542 1.905  1.905  1.8796 1.7526 1.8034 1.8796
 1.8542 1.8542 1.9304 1.8796 1.8796 1.778  1.8288 1.9558 1.8796 1.778
 1.8542 1.905  1.9304 1.9304 1.9812 1.8796 1.8796 1.9304 1.9558 2.0574
 1.9812 1.905  1.9558 1.905  1.9304 1.8796 1.8288 1.8288 1.905  1.8542
 1.8542 1.8542 1.778  1.778  1.778  1.9304 1.7272 1.8034 1.8288 1.905
 1.905  1.905  1.905  1.7272 1.

## 2. Calculate Volleyball player's weight and find out the BMI?

height_inches is in inches and weight_lb is in pounds.

It's now possible to calculate the BMI of each Volleyball player. Code to convert height_inches to a numpy array with the correct units is already available. Follow the instructions step by step and finish the game!

### Instructions
* Create a numpy array from the `weight_lb` list with the correct units. Multiply by `0.453592` to go from pounds to kilograms. Store the resulting numpy array as `np_weight_kg`.
* Use `np_height_metres` and `np_weight_kg` to calculate the BMI of each player. Use the following equation:
 $$ \text{BMI}=\frac{\text{weight(kg)}}{\text{height(m)}^2}$$
* Save the resulting numpy array as `bmi`.
* Print out `bmi`.


In [3]:
weight_lb=[180, 215, 210, 210,205, 230, 195, 180, 192, 225, 203, 195, 182, 188, 200, 180, 200, 200, 245, 240, 215, 185, 175, 199, 
           200, 215, 200, 205, 206, 186, 188, 220, 210, 195, 200, 200, 212, 224, 210, 205, 220, 195, 200, 260, 228, 270, 200, 210, 
           190, 220, 180, 205, 210, 220, 211, 200, 180, 190, 170, 230, 155, 185, 185, 200, 225, 225, 220, 160, 205, 235, 250, 210, 
           190, 160, 200, 205, 222, 195, 205, 220, 220, 170, 185, 195, 220, 230, 180, 220, 180, 180, 170, 210, 215, 200, 213, 180, 
           192, 235, 185, 235, 210, 222, 210, 230, 220, 180, 190, 200, 210, 194, 180, 190, 240, 200, 198, 200, 195, 210, 220, 190, 
           210, 225, 180, 185, 170, 185, 185, 180, 178, 175, 200, 204]

np_weight_kg = np.array(weight_lb)*0.453592
bmi = np_weight_kg/np_height_meters**2
bmi


array([23.11037639, 27.60406069, 28.48080465, 28.48080465, 27.04618995,
       33.96468629, 28.79614707, 25.10462629, 23.37071489, 31.38078286,
       26.78232468, 25.72686361, 23.36715835, 24.13750423, 29.53450981,
       25.82702472, 26.38652678, 24.99800911, 28.31227918, 27.0367828 ,
       26.17033177, 23.75233129, 21.30143284, 26.98895297, 27.89402921,
       26.87285979, 23.71627614, 26.32015089, 27.17812259, 23.88072227,
       21.72534076, 29.02517946, 26.24790956, 25.72686361, 24.99800911,
       24.99800911, 27.21888775, 33.07865099, 29.28873067, 26.32015089,
       29.02517946, 25.72686361, 24.34449467, 33.38165478, 29.27314343,
       38.74053707, 27.12457585, 24.90208995, 24.39428619, 31.56636354,
       23.7478741 , 25.62295933, 25.56171941, 26.77894414, 24.38322819,
       25.67819599, 23.11037639, 23.12726994, 20.15883472, 24.64652818,
       17.91185009, 23.12315842, 21.93755543, 24.99800911, 27.38755651,
       28.88797049, 29.83703344, 21.69966068, 25.62295933, 31.00

## Calculate the Lightweight Volleyball players whose EMI is below 21?
### Instructions
* Create a boolean numpy array: the element of the array should be True if the corresponding volleyball player's     BMI is below 21. You can use the `<` operator for this. Name the array `light`.
* Print the array `light`.
* Print out a numpy array with the BMIs of all volleyball players whose BMI is below 21. Use light inside square     brackets to do a selection on the bmi array.

In [4]:
light = bmi <21
bmi[light]

array([20.15883472, 17.91185009, 19.64525494])

## 4. Find the number of people who have exceptional height?
### Instructions
* The array `np_height_inches` is already given for you.
* Calculate the 95th percentile value of height and save it in variable `h`
* Calculate the number of people having height greater than 95th percentile value.

In [5]:
h = np.percentile(np_height_inches,95)
eh = np_height_inches > h
np_height_inches[eh]

array([79, 81, 79, 80])